# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Theme Settings
#theme: minima
#theme                  : "minimal-mistakes-jekyll"
#remote_theme: "mmistakes/minimal-mistakes@4.20.1"
remote_theme: hydecorp/hydejack@v9.0.4
#minimal_mistakes_skin  : "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
url: https://codethatmath.com
baseurl: ''

accent_image: https://sophiesophie.s3.eu-central-1.amazonaws.com/album1/f02.jpg
accent_color: rgb(0,255,0) # hero color also (if no image provided)

font:         Noto Sans, Helvetica, Arial, sans-serif
font_heading: Lato, Helvetica, Arial, sans-serif
google_fonts: Lato:400|Noto+Sans:400,400i,700,700i

author:
  name:  Alexander Shamanskiy
  email: shamanskiy@codethatmath.com
  about: |
    Hi, I'm Alex, a mathematician/software engineer. I like finding new ways to ...
  picture:  https://codethatmath.s3.eu-central-1.amazonaws.com/autor_image.jpg
  social:
    github: shamanskiy
    Linkedin: https://www.linkedin.com/in/shamanskiy
    researchgate: https://www.researchgate.net/profile/Alexander_Shamanskiy
    email: shamanskiy@codethatmath.com

disqus: codethatmath

google-analytics: UA-179576532-1

defaults:
  - scope:
      type: posts
    values:
      comments: true




# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
